#!/bin/sh
#-
# Copyright (c) 2011 Nathan Whitehorn
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions
# are met:
# 1. Redistributions of source code must retain the above copyright
#    notice, this list of conditions and the following disclaimer.
# 2. Redistributions in binary form must reproduce the above copyright
#    notice, this list of conditions and the following disclaimer in the
#    documentation and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE AUTHOR AND CONTRIBUTORS ``AS IS'' AND
# ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
# ARE DISCLAIMED.  IN NO EVENT SHALL THE AUTHOR OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS
# OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION)
# HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT
# LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY
# OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF
# SUCH DAMAGE.
#
# $FreeBSD$

: ${DIALOG_OK=0}
: ${DIALOG_CANCEL=1}
: ${DIALOG_HELP=2}
: ${DIALOG_EXTRA=3}
: ${DIALOG_ITEM_HELP=4}
: ${DIALOG_ESC=255}

exec 3>&1
MIRROR=`dialog --backtitle "HardenedBSD Installer" \
    --title "Mirror Selection - experimental and not all branch supported" --extra-button --extra-label "Other" \
    --menu "Please select the site closest to you or \"other\" if you'd like to specify a different choice.  Also note that not every site listed here carries more than the base distribution kits. Only Primary sites are guaranteed to carry the full range of possible distributions. Select a site that's close!" \
    0 0 0 \
	http://jenkins.hardenedbsd.org	"Main Site"\
	http://jenkins.hardenedbsd.org 	"IPv6 Main Site"\
    2>&1 1>&3`
MIRROR_BUTTON=$?
exec 3>&-

_UNAME_R=`uname -r`
_UNAME_R=${_UNAME_R%-p*}

#
# XXX:	We should create the proper infrastructure to serve these distfiles.
# 	Currently this isn't supported.
#

#case ${_UNAME_R} in
#	*-CURRENT|*-STABLE|*-PRERELEASE)
#		RELDIR="snapshots"
#		;;
#	*)
#		RELDIR="releases"
#		;;
#esac
#
#BSDINSTALL_DISTSITE="$MIRROR/pub/HardenedBSD/${RELDIR}/`uname -m`/`uname -p`/${_UNAME_R}"

#
# XXX: hard-code paths...
#
case ${_UNAME_R} in
	*-STABLE-HBSD|*-PRERELEASE-HBSD)
		_HBSD_MAJOR=${_UNAME_R%.*}
		BSDINSTALL_DISTSITE="$MIRROR/builds/HardenedBSD-stable-${_HBSD_MAJOR}-STABLE-`uname -m`-LATEST"
		;;
	*-CURRENT-HBSD)
		BSDINSTALL_DISTSITE="$MIRROR/builds/HardenedBSD-stable-master-`uname -m`-LATEST"
		;;
	*)
		BSDINSTALL_DISTSITE="XXX not handled by the current state XXX"
		;;
esac

case $MIRROR_BUTTON in
$DIALOG_CANCEL)
	exit 1
	;;
$DIALOG_OK)
	;;
$DIALOG_EXTRA)
	exec 3>&1
	BSDINSTALL_DISTSITE=`dialog --backtitle "HardenedBSD Installer" \
	    --title "Mirror Selection" \
	    --inputbox "Please enter the URL to an alternate HardenedBSD mirror:" \
	    0 0 "$BSDINSTALL_DISTSITE" 2>&1 1>&3`
	MIRROR_BUTTON=$?
	exec 3>&-
	test $MIRROR_BUTTON -eq 0 || exec $0 $@
	;;
esac

export BSDINSTALL_DISTSITE
echo $BSDINSTALL_DISTSITE >&2
