FILES=	ca.hardenedbsd.org

FILESDIR=	${SHAREDIR}/keys/hbsd-update/trusted
FILESMODE=	444

SYMLINKS=		${SHAREDIR}/keys/hbsd-update/trusted/ca.hardenedbsd.org ${SHAREDIR}/keys/hbsd-update/trusted/5905e1b4.0

.include <bsd.prog.mk>
